-fwdflat no -bestpath yes -inmic yes
-hmm ../../../model/en-us/en-us
-lm ../../../model/en-us/en-us.lm.bin
-dict ../../../model/en-us/cmudict-en-us.dict
-hmm ../../../model/en-us2/en-us
-lm ../../../model/en-us2/en-us.lm.bin
-dict ../../../model/en-us2/cmudict-en-us.dict
